name: Instagram Auto Publisher

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        with:
          python-version: '3.11'
        uses: actions/setup-python@v4

      - name: Install Libraries
        run: |
          pip install requests Pillow instagrapi gspread google-auth oauth2client

      - name: Run Script
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python main.py
